### ISSUE TITLE
Improving CSS

### ISSUE THREAD

**Issue by alphayowakarindi** [Lizdev-05/Portfolio#10]
### Highlights

- Great descriptive commits :heavy_check_mark: 
- Correct use of GitHub flow :heavy_check_mark: 
- Linters check passed :heavy_check_mark: 
- Professional README.md :heavy_check_mark: 

### Changes :recycle: 

- Have your font-family property and value in the body tag only to avoid repeating it many blocks hence making your code less verbose and easy to maintain. In the future, if you want to change your font family you'll only change it in one place, the body tag.
- Use overflow hidden for the body tag to prevent overflow for the entire page.
- Erase the commented out code from the CSS file that is not executed to make your code cleaner

**Comment by Lizdev-05** [comment]
Okay, thank you all for pointing these issues out. I will work on it.
